### ISSUE TITLE
error: The following required arguments were not provided: --common-labels <common-labels>

### ISSUE THREAD

**Issue by efstathiosntonas** [afitzek/hasura-metric-adapter#23]
Hi, I'm using version `1.0.8` and it throws this error: 

`error: The following required arguments were not provided: --common-labels <common-labels>`

Here's my `docker-compose.yaml`

```yml
services:
  postgres:
    image: postgis/postgis:14-3.2-alpine
    command: postgres -c 'max_connections=1000'
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  graphql-engine:
    image: hasura/graphql-engine:v2.14.0-beta.1-ce.cli-migrations-v3
    command: sh -c 'rm -rf /tmp/log/stdout.log && mkfifo /tmp/log/stdout.log && /bin/graphql-engine serve | tee /tmp/log/stdout.log'
    ports:
      - "8080:8080"
      - "3000:3000"
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./hasura/migrations:/hasura-migrations
      - ./hasura/metadata:/hasura-metadata
      - logs:/tmp/log
    environment:
      GCP_PROJECT_ID: "${FIREBASE_PROJECT_ID}"
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      POSTGRES_DB_USER: postgres
      POSTGRES_DB_PASSWORD: postgrespassword
      POSTGRES_DB_HOST: postgres
      #HASURA_GRAPHQL_ADMIN_INTERNAL_ERRORS: "true"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false" # set to "false" as we use console served by hasura-cli
      HASURA_GRAPHQL_DEV_MODE: "true" # It is recommended to disable this in production
      HASURA_GRAPHQL_JWT_SECRET: '{
        "allowed_skew": 5000,
        "audience": "${FIREBASE_PROJECT_ID}",
        "issuer": "https://securetoken.google.com/${FIREBASE_PROJECT_ID}",
        "jwk_url": "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com",
        "type":"RS256"
        }'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup,query-log,http-log,webhook-log,websocket-log
      HASURA_GRAPHQL_EXPERIMENTAL_FEATURES: optimize_permission_filters, streaming_subscriptions
      HASURA_GRAPHQL_ENABLE_METADATA_QUERY_LOGGING: "true" # the query and raw-query field from http-logs for metadata requests are removed by default
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_INFER_FUNCTION_PERMISSIONS: "false"
      CLOUD_FUNCTIONS_BASE_URL: "http://host.docker.internal:3000"
      HASURA_GRAPHQL_LOG_LEVEL: "info"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "anonymous"
      HASURA_GRAPHQL_MIGRATIONS_SERVER_TIMEOUT: 60

  hasura-metric-adapter:
    build:
      context: ./
      dockerfile: Dockerfile
    image: hasura-metric-adapter:1.0.8
    ports:
      - "9090:9090"
    depends_on:
      - "graphql-engine"
    volumes:
      - logs:/tmp/log
    environment:
      LOG_FILE: /tmp/log/stdout.log
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_ENDPOINT: "http://hasura:8080"
      EXCLUDE_COLLECTORS: "cron-triggers;event-triggers;scheduled-events"
#      COMMON_LABELS: "collector="
#      LISTEN_ADDR:

  prometheus:
    image: prom/prometheus:v2.30.3
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3001:3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/dashboards
volumes:
  db_data:
  logs:
  prometheus-data:
```
